# Generated by Django 3.2.6 on 2022-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Разместите фото для объявления', null=True, upload_to='images/', verbose_name='фото'),
        ),
    ]
