# Generated by Django 3.2.6 on 2022-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Укажите, активен ли аккаунт', verbose_name='Аккаунт активен'),
            preserve_default=False,
        ),
    ]
