# Generated by Django 3.2.6 on 2022-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите имя, максимальное количество символов: 64', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию, максимальное количество символов: 64', max_length=64, verbose_name='Фамилия'),
        ),
    ]
